# This workflow will install Python dependencies, run tests and lint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Zivid SDK
      run: |
        cd $GITHUB_WORKSPACE
        mkdir Zivid
        cd Zivid
        wget \
        https://downloads.zivid.com/sdk/releases/2.9.0+4dbba385-1/u22/zivid-telicam-driver_3.0.1.1-3_amd64.deb \
        https://downloads.zivid.com/sdk/releases/2.9.0+4dbba385-1/u22/zivid_2.9.0+4dbba385-1_amd64.deb
        sudo apt install ./*.deb
        cd $GITHUB_WORKSPACE
        rm -rf Zivid
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        pytest
